### ISSUE TITLE
Orphan Pages Review - 8 Pages

### ISSUE THREAD

**Issue by StraightUpSearch** [tutorcruncher/website-new#28]
Issue details

Orphan pages of a website have no incoming internal links.

Search engine crawlers can only discover such pages from the sitemap file or from external backlinks. Website visitors won't be able to get to this page from any other page on your website.

How to fix
Check your website navigation and [link architecture](https://webmasters.googleblog.com/2008/10/importance-of-link-architecture.html) to make sure all relevant pages are easily accessible.

[Learn more](https://help.ahrefs.com/site-audit/issues/orphan-page-error-in-site-audit)

FULL LIST: only 8 pages
https://docs.google.com/spreadsheets/d/1n_jKIIvtGdpd7e3dweegzq5idzQ490JFxG__GU_65_M/edit?usp=sharing

**Comment by StraightUpSearch** [comment]
https://tutorcruncher.com/test-ignore - easy one, can we delete it?

**Comment by codetopixels** [comment]
@StraightUpSearch This has been deleted.

**Comment by tomhamiltonstubber** [comment]
- [ ] https://tutorcruncher.com/online-tutoring **Needs fixed**
- [ ] https://tutorcruncher.com/test-ignore **Deleted**
- [ ] https://tutorcruncher.com/book-a-call/2 **Can be got to via the book-a-call page
- [ ] https://tutorcruncher.com/book-a-call/9 **Can be got to via the book-a-call page
- [ ] https://tutorcruncher.com/external-resources **Needs fixed**
- [ ] https://tutorcruncher.com/book-a-call/1 **Can be got to via the book-a-call page
- [ ] https://tutorcruncher.com/features/support **Referenced on Features page**
- [ ] https://tutorcruncher.com/features/communications **Referenced on Features page**

**Comment by StraightUpSearch** [comment]
Thanks Tom, shall I close this off or should we wait for the fixes?
