### ISSUE TITLE
Homepage SEO Modifications - Title & Heading (Minor)

### ISSUE THREAD

**Issue by StraightUpSearch** [tutorcruncher/website-new#30]
Current meta:

![image](https://github.com/user-attachments/assets/8acc4025-fa09-4485-b6d7-a9d210df94f2)

Proposed change:

**TITLE**
The #1 Tutor Management Software - TutorCruncher

**META DESC**
Tutor management software to automate scheduling, payments + admin for tutoring businesses. Boost efficiency with TutorCruncher. Try it today!

**ALTERNATE, if you don't like the above title:**
TutorCruncher - The Leading Tutor Management Software Solution

**OR**
Tutor Management Software | Save Time & Streamline Operations

____________

Seperate issue, I've noticed that the following are wrapped in headings:
![image](https://github.com/user-attachments/assets/2dec3130-ae86-467d-80ee-a7611231bf34)
![image](https://github.com/user-attachments/assets/ff6ebc44-93eb-45bd-8128-28d71430c7d8)

Can this be removed? (e.g. you can have same styling, size - but don't put in a H2)

**Comment by codetopixels** [comment]
@tomhamiltonstubber  & @StraightUpSearch. Heading in the drop down solution menu has been updated to no longer be a heading

**Comment by tomhamiltonstubber** [comment]
Let's go for 'TutorCruncher - The Leading Tutor Management Software Solution' as the meta title
